Cllog/Script/addNewDomain.sh
Cllog/Script/addNewFeature.sh

- make 실행 시, service가 .sample로 생성되어 발생하는 오류 해결했습니다
- .sample -> .cllog로 변경

[Fix] make 명령 오류 해결

---

Cllog/Projects/AppModule/Sample/Sources/SampleApp.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/AuthTokenResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Login/LoginDataSource.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/Login/DefaultLoginRepository.swift
Cllog/Projects/CllogService/Domains/Domain/Project.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Project.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Repository/LoginRepository.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Sample.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/UseCase/KakaoLogin.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/UseCase/LoginUseCase.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Tests/Sources/Sample.swift
Cllog/Projects/CllogService/Features/LoginFeature/Demo/Resources/Sample.swift
Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/App.swift
Cllog/Projects/CllogService/Features/LoginFeature/Demo/Sources/AppDelegate.swift
Cllog/Projects/CllogService/Features/LoginFeature/Interface/Sources/Sample.swift
Cllog/Projects/CllogService/Features/LoginFeature/Project.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
Cllog/Projects/CllogService/Features/LoginFeature/Test/Sources/Sample.swift
Cllog/Projects/CllogService/Features/LoginFeature/Tests/Sources/Sample.swift
Cllog/Projects/CllogService/Service/Project.swift
Cllog/Tuist/Package.resolved
Cllog/Tuist/Package.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Domain.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift
Cllog/Tuist/ProjectDescriptionHelpers/Template/Project+Template.swift

- LoginFeature 기본 구조 정의 (Clean Architecture & TCA)
- TCA 추가 및 Snapkit 삭제
- develop 아닌 login branch에 머지할 예정입니다. 카카오 및 애플 로그인 기능 완료 후 디벨롭에 머지하겠습니다!
- Feature Demo 앱 빌드 안 되는 문제 해결 (준영님)
-

[SPS-53] LoginFeature 설계 작업

---

README.md

-
- [지라 링크](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1/backlog?selectedIssue=SPS-62)
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-62] 리드미 기술 스택 추가

---

Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
Cllog/Projects/AppModule/Sample/Sources/Core/ClLogPhase.swift
Cllog/Projects/AppModule/Sample/Sources/Core/ClLogWindow.swift
Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
Cllog/Projects/AppModule/Sample/Sources/Service/Home/HomeViewController.swift
Cllog/Projects/AppModule/Starlink/Project.swift
Cllog/Projects/AppModule/Starlink/Sources/Configure/Configure.swift
Cllog/Projects/AppModule/Starlink/Sources/ConsoleWIndow/ConsoleWIndow.swift
Cllog/Projects/AppModule/Starlink/Sources/Delegate/StarlinkDelegate.swift
Cllog/Projects/AppModule/Starlink/Sources/Interceptor/Interceptor.swift
Cllog/Projects/AppModule/Starlink/Sources/Request/Request.Response.swift
Cllog/Projects/AppModule/Starlink/Sources/Session/Session.swift
Cllog/Projects/AppModule/Starlink/Sources/Starlink.swift
Cllog/Projects/AppModule/Starlink/Sources/Tracking/Tracking.swift
Cllog/Tuist/Package.resolved
Cllog/Tuist/Package.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift

- 네트워크 로그를 새로운 윈도우에서 노출하게 변경
- 흔들기 기능으로 다시 노출하게 추가
- 추후에 펼치기, 전체 화면이동 기능을 추가하면 좋을듯
- pulse 라이브러리 추가
- 새로운 window생성
- ClLogPhase 생성
- [지라](https://depromeet-16-5.atlassian.net/browse/SPS-64)
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[feat] Console 추가

---

Cllog/Projects/AppModule/Sample/Resources/GoogleService-Info.plist
Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Cllog/Projects/CllogService/CoreKit/Core/Project.swift
Cllog/Tuist/Package.resolved
Cllog/Tuist/Package.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-67] 파이어페이스 연동

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/GeneralButton.swift

- 디자인 시스템 General 버튼 SwiftUI 작업
- [지라 링크](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-76)
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-76] 디자인 시스템 General 버튼 작업

---

Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Fonts.swift

- SwInject를 활용하여 register
- Swinject를 활용하여 ClLogFont Register를 변경
- register를 하는 
[ClLog DI](https://depromeet-16-5.atlassian.net/browse/SPS-75)

[SPS-75] [iOS] ClLogFont DI

---

Cllog/Projects/CllogService/Features/LoginFeature/Project.swift
Cllog/Tuist/Package.resolved
Cllog/Tuist/Package.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Library.swift

- #26 체리픽 도중 해당 작업 내역 삭제되어.. 다시 올립니다

[SPS-53] FIX: firebase spm

---

Cllog/Projects/AppModule/Sample/Sources/Service/Home/Feature/HomeFeature.swift
Cllog/Projects/AppModule/Sample/Sources/Service/Home/View/HomeView.swift
Cllog/Projects/AppModule/Sample/Sources/Service/Home/View/HomeViewController.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Demo/Resources/Sample.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Demo/Sources/App.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Demo/Sources/AppDelegate.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Interface/Sources/Sample.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Project.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Sources/CaptureFeature.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Sources/CaptureView.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Test/Sources/Sample.swift
Cllog/Projects/CllogService/Features/CaptureFeature/Tests/Sources/Sample.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
Cllog/Projects/CllogService/Features/MainFeature/Sources/MainFeature.swift
Cllog/Projects/CllogService/Features/MainFeature/Sources/MainView.swift
Cllog/Projects/CllogService/Features/MainFeature/Sources/Sample.swift
Cllog/Projects/CllogService/Service/Project.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift

- 앱 러칭시 구조 설계
- Tab 구조
- TCA 적용
- TCA구조 설계
- 앱 러칭시 구조
- TabView 적용
- TCA가 처음이라 구조적이 리뷰가 필요
[초기 세팅](https://depromeet-16-5.atlassian.net/browse/SPS-65)

[SPS-65] 초기 화면 세팅

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recodeButton.imageset/Contents.json
Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recodeButton.imageset/recode_button.svg
Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recordingButton.imageset/Contents.json
Cllog/Projects/CllogService/CoreKit/DesignKit/Resources/Asset/Assets.xcassets/recordingButton.imageset/recording_button.svg
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/RecodingButton.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/ClLogUI.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/DesignSystem/Image.swift

-
- [지라 링크](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-82)
관련 로그, 스크린샷
---
| before | after |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/1af80107-dadc-4f0f-bef9-25db588d8eea" /> | <img src="https://github.com/user-attachments/assets/04517934-b1d9-44cc-9f32-707aa394e28e" /> |
| 작업전 | 작업후 |
| --- | --- |

[SPS-82] 레코딩 버튼 작업

---

Cllog/Projects/AppModule/Starlink/Sources/Error/Error.swift
Cllog/Projects/AppModule/Starlink/Sources/Lock/SafeDictionary.swift
Cllog/Projects/AppModule/Starlink/Sources/Request/Request.Response.swift
Cllog/Projects/AppModule/Starlink/Sources/Starlink.swift

- encodeable을 받을수있게 수정
- 크래시 수정
- Encodable을 채택한 모델을 파라미터로 넣을수있게 수정
[SPS-84](https://depromeet-16-5.atlassian.net/browse/SPS-84)
[SPS-84]: https://depromeet-16-5.atlassian.net/browse/SPS-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-84] [iOS] 네트워크 개발 - Encodable하게 받게 수정

---

Cllog/Projects/CllogService/Data/Data/Sources/API/APIService.swift
Cllog/Projects/CllogService/Data/Data/Sources/API/EndpointType.swift
Cllog/Projects/CllogService/Data/Data/Sources/API/LoginAPI.swift
Cllog/Projects/CllogService/Data/Data/Sources/API/ParameterType.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/AuthTokenRequestDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultLoginRepository.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Repository/LoginRepository.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/UseCase/LoginUseCase.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift

- 애플 연결
- [SPS-53](https://depromeet-16-5.atlassian.net/issues/SPS-53?filter=-1)
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |
[SPS-53]: https://depromeet-16-5.atlassian.net/browse/SPS-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 애플 로그인 연결

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/CompleteOrFailChip.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/LevelChip.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/TitleWithImageChip.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Chip/VideoTimeChip.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/Tooltip.swift

- VideoTimeChip & Tooltip 개발
-- 프리뷰는 지라 티켓에 이미지 첨부했어!
- https://depromeet-16-5.atlassian.net/browse/SPS-90

[SPS-90] UI Component - VideoTimeChip & Tooltip 개발

---

Cllog/Projects/AppModule/Sample/Sources/Core/ClLogApp.swift
Cllog/Projects/CllogService/Data/Data/Sources/Storage/AppData.swift
Cllog/Projects/CllogService/Data/Data/Sources/Storage/KeychainItemType.swift
Cllog/Projects/CllogService/Data/Data/Sources/Storage/KeychainManager.swift
Cllog/Projects/CllogService/Data/Data/Sources/Storage/KeychainWrapper.swift
Cllog/Projects/CllogService/Data/Data/Sources/Storage/UserDefaultWrapper.swift
Cllog/Projects/CllogService/Domains/LoginDomain/Sources/Depenency/LoginUseCaseKey.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift
Cllog/Projects/CllogService/Modules/Shared/Sources/ClLogDI.swift
Cllog/Projects/CllogService/Modules/Shared/Sources/Sample.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Home/Feature/HomeFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeViewController.swift

- keychain 저장 객체 생성
- AccessToken keychain 저장
- 현재 Access token response 저장 시 크래시 나는 문제 해결
- Decodable 객체이기 때문에 @UserDefaultArray로 저장해야하는데, UserDefault로 저장함.
- UserDefault 코더블 저장 객체 삭제
- 기본 값만 저장 또는 일반 모델로 변경하여 저장하도록 협의
- [SPS-92](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-92)
[SPS-92]: https://depromeet-16-5.atlassian.net/browse/SPS-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-92] Keychain 저장 객체 생성 및 access token 저장

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Project.swift
Cllog/Projects/CllogService/Modules/ThirdPartyLibrary/Project.swift

- 전체에서 접근할 수 있도록 변경
- Design kit에서 TCA 사용가능하도록 library kit 연결 ㅠ
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[Fix] Composable architecture 위치 변경

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/AuthTokenDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Local/TokenDataSource.swift
Cllog/Projects/CllogService/Data/Networker/Sources/Interceptor/TokenInterceptor.swift
Cllog/Projects/CllogService/Data/Networker/Sources/Model/TokenDTO.swift
Cllog/Projects/CllogService/Data/Networker/Sources/Provider/AuthProvider.swift
Cllog/Projects/CllogService/Data/Networker/Sources/Provider/Provider.swift

- token interceptor 생성
```swift
public struct ClLogServiceAssembly: Assembly {
public init() {}
public func assemble(container: Container) {
container.register(LoginUseCase.self) { _ in
DefaultLoginUseCase(
loginRepository: DefaultLoginRepository(
authDataSource: DefaultAuthDataSource(
provider: AuthProvider(
tokenProvider: DefaultTokenDataSource().loadToken)
),
tokenDataSource: DefaultTokenDataSource()
)
)
}
}
}
```
- [SPS-111](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-111)
- 앱 요청 관련 interceptor도 넣을게유
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |
[SPS-111]: https://depromeet-16-5.atlassian.net/browse/SPS-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SPS-111] TokenInterceptor 생성

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift

- thumbnail view 생성
- [115](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-115)
관련 로그, 스크린샷
---
| 디자인 시스템 | 작업 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/9f3149fb-b5cb-456b-a8ef-2894997de6fa)|<img width="307" alt="image" src="https://github.com/user-attachments/assets/d91e1910-0ead-4318-ab2b-fd8c69e33ed4" />|

[SPS-115] Thumbnail View 생성

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Core/Extension/Color+Extension.swift
Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift

- 로그인 화면 디자인 적용
- [124](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-124)
관련 로그, 스크린샷
---
| iphone 16 pro | iPhone SE|
| --- | --- |
|![Simulator Screenshot - iPhone 16 Pro - 2025-03-09 at 05 03 39](https://github.com/user-attachments/assets/87f53a4d-c636-4993-8c4c-9b5999cba488)|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-03-09 at 05 05 45](https://github.com/user-attachments/assets/901c23ea-eb6d-4cbb-ac12-0de8263b0a4a)|

[SPS-124] 로그인 화면 디자인 적용

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/AppBar/AppBar.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Demo/Sources/App.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Main/CalendarMainView.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift

- 캘린더 상세정보 화면 UI 작업
- [지라 링크](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-99)
관련 로그, 스크린샷
---

feat. 캘린더 상세 UI 작업

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/ClLogTextInput.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/TextInputConfiguration.swift

- TextField -> TextInput (연산자를 통해서 feild, editor를 선택해서 사용 가능하게 만들었습니다.)
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

fix. 텍스트 필드 수정

---

Cllog/Projects/CllogService/CoreKit/Core/Sources/Extension/String+Extension.swift
Cllog/Projects/CllogService/CoreKit/Core/Sources/Helper/ConsonantSearcherHelper.swift
Cllog/Projects/CllogService/CoreKit/Core/Sources/Sample.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/TwoLineRow.swift
Cllog/Projects/CllogService/Domains/FolderDomain/Sources/Repository/CragRepository.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/FolderFeature.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/FolderView.swift
Cllog/Projects/CllogService/Modules/Shared/Sources/Entity/Crag.swift

-
- [129](https://depromeet-16-5.atlassian.net/browse/SPS-129)
관련 로그, 스크린샷
---
https://github.com/user-attachments/assets/6123600d-f18c-40a1-8d1c-e2db5cf27e13
https://github.com/user-attachments/assets/403a2c6a-bb47-4ced-8906-facba3f9352a

[SPS-129] 클라이밍 목록 선택 및 검색 기능

---

Cllog/Projects/AppModule/Sample/Sources/Core/SceneDelegate.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/FolderFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeView.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Home/View/HomeViewController.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift

- [지라 링크](https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-143)
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-143] 캘린더 디테일 화면 push 작업

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/CragBottomSheet.swift

- UI
- 
- 디바운싱 없음 -> 각 뷰에서 처리
- 이벤트 전달이 안됨. 추후에 수정!
- 암장 정보 리스트뷰 우선 고정높이로 제공 -> TODO 수정 필요
-https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-149
관련 로그, 스크린샷
---
https://github.com/user-attachments/assets/67c37d41-ef20-4642-af1f-6d874f1ee6af

[SPS-149] 암장 검색 및 선택

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift
Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditView.swift

- 스탬프 기능 오동작 수정
- https://depromeet-16-5.atlassian.net/browse/SPS-122

[SPS-122] 영상 편집 - 스탬프 버튼을 통한 중요 부분 기록

---

Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultTokenRepository.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefualtWithdrawRepository.swift
Cllog/Projects/CllogService/Data/Networker/Sources/Model/TokenDTO.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/TokenRepository.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/WithdrawRepository.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/LoginTypeFetcher/LoginTypeFetcherUseCase.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Logout/LogoutUseCase.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Withdraw/WithdrawUseCase.swift
Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-103] 회원 탈퇴

---

Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultTokenRepository.swift
Cllog/Projects/CllogService/Data/Networker/Sources/Model/TokenDTO.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/TokenRepository.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/LoginTypeFetcher/LoginTypeFetcherUseCase.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/ValidateUserSession/ValidateUserSessionUseCase.swift
Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashFeature.swift
Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashView.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-170] 자동 로그인 적용

---

Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Local/TokenDataSource.swift

[hotfix] access token 접근

---

Cllog/Projects/CllogService/CoreKit/Core/Sources/View/Router/EnableBackSwipeModifier.swift
Cllog/Projects/CllogService/CoreKit/Core/Sources/View/WebView/WebView.swift
Cllog/Projects/CllogService/CoreKit/Core/Sources/View/WebView/WebViewFeature.swift
Cllog/Projects/CllogService/CoreKit/Tests/Sources/Sample.swift
Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingView.swift
Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/UIModel/SettingItemType.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/Path.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-169] 개인정보 처리 방침, 서비스 이용약관 WebView 작업

---

Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultDeleteStoryRepository.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultStoryRepository.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Repository/DeleteStoryRepository.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/DeleteStoryUseCase.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailFeature.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/CalendarDetail/CalendarDetailView.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-158] 캘린더 스토리 삭제 작업

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/Tooltip.swift
Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/EditFeatureTooltipManager.swift
Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditView.swift

- 영상 편집 - 툴팁 관리
- https://depromeet-16-5.atlassian.net/browse/SPS-162

[SPS-162] 영상 편집 - 툴팁 관리

---

Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-186] 동영상 촬영 후 편집화면 이동

---

Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-187] 영상 촬영 종료 작업

---

Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/VideoRecordRepositry.swift
Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/CaptureRepository.swift
Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/Video/VideoUseCase.swift
Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-191] 사진첩 저장 기능

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/FolderButton.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/NextProblemButton.swift
Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Entity/Story/SavedStory.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recording/RecordingFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recording/RecordingView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/UserDefault/VideoDataManager.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-192] 영상 촬영 UI 작업

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/BaseResponse/MetaResponseDTO.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedView.swift

- 난이도 및 암장 정보 조회
- UserDefault 저장 및 Level chip 연결
- 커서 기반 페이지네이션
- 검색 필터링
- https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1/backlog?selectedIssue=SPS-59
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-59] 난이도 및 암장 정보 조회

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/GradeBottomSheet.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/BaseResponse/MetaResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultAttemptRepository.swift
Cllog/Projects/CllogService/Domains/FolderDomain/Sources/Repository/AttemptRepository.swift
Cllog/Projects/CllogService/Domains/FolderDomain/Sources/UseCase/AttemptUseCase.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedView.swift

- 수정 후 데이터로 ui 업데이트
- 잘못 수정되는 오류 수정
- 바텀시트 닫힌 후, 기존 데이터 캐싱되는 오류 해결
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-174] FIX: 암장 수정 오류 수정

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/CragBottomSheet.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/GradeBottomSheet.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/BaseResponse/MetaResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/CragDataSource.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultCragRepository.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultNearByCragRepository.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/Repository/NearByCragRepository.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/CragUseCase.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/NearByCragUseCase.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedView.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift

- TODO: 추후 crag repository 삭제 예정입니다
- https://depromeet-16-5.atlassian.net/browse/SPS-198
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-198] 암장 페이지네이션 및 검색어 필터링

---

Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift
Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-200] 권한 요청 시점 변경 및 추적 권한 추가

---

Cllog/Projects/CllogService/Data/Data/Sources/Repository/VideoRecordRepositry.swift
Cllog/Projects/CllogService/Domains/VideoDomain/Sources/Repository/CaptureRepository.swift
Cllog/Projects/CllogService/Domains/VideoDomain/Sources/UseCase/Video/VideoUseCase.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-203] 사진첩에 영상 저장

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/GradeBottomSheet.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/SelectGradeView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift

- 팁 ui는 업승ㅁ
- https://depromeet-16-5.atlassian.net/browse/SPS-206
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-206] 다음문제 선택 시 난이도 변경 뷰 출력

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryResponseDTO.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/Story.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/FetchStoryUseCase.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Stories/StoriesFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheet.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheetFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-201] 종료 버튼 탭 UserDefault 삭제 작업

---

Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift

-
- https://depromeet-16-5.atlassian.net/browse/SPS-206
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-206] 다음문제 선택 시, 변경된 난이도 정보 표기되지 않는 문제 해결

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Report/ReportResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryAttemptResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryProblemResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Story/StoryResponseDTO.swift
Cllog/Projects/CllogService/Domains/ReportDomain/Sources/Entity/Report.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/Story.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryAttempt.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Story/StoryProblem.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/FetchStoryUseCase.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Stories/StoriesFeature.swift
Cllog/Projects/CllogService/Features/ReportFeature/Sources/Presentation/ReportView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckBottomSheet.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheetFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-212] 폴더탭 및 레포트 버그 수정

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/ClLogTextInput.swift
Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/TextInput/TextInputConfiguration.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Account/UserNameRequestDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Account/UserResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultAccountRepository.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Entity/User.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/Repository/AccountRepository.swift
Cllog/Projects/CllogService/Domains/AccountDomain/Sources/UseCase/Account/AccountUseCase.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Demo/Resources/Sample.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Demo/Sources/App.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Demo/Sources/AppDelegate.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Interface/Sources/Sample.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Project.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Sources/Presentation/NickNameFeature.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Sources/Presentation/NickNameView.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Sources/Sample.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Sources/UIModel/NickNameViewState.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Test/Sources/Sample.swift
Cllog/Projects/CllogService/Features/NickNameFeature/Tests/Sources/Sample.swift
Cllog/Projects/CllogService/Features/SplashFeature/Sources/Presentation/SplashFeature.swift
Cllog/Projects/CllogService/Service/Project.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Root/View/RootView.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-235] 최초 가입시 닉네임 설정

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift

- 좌측 트리밍 핸들과 playHead가 만나면 재생 안되는 이슈 수정
- https://depromeet-16-5.atlassian.net/browse/SPS-232
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-232][영상 편집] 좌측 트리밍 핸들과 playHead가 만나면 재생 안되는 이슈 수정

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Progress/PlayerProgressBar.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedPlayView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedPlayViewModel.swift

- 이제 편집 잘됨
- 두번째 편집 시도만 수정필요
- https://depromeet-16-5.atlassian.net/browse/SPS-233
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-233][영상 편집] 영상 구간 편집 안되는 이슈 수정

---

Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheet.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordedProblems/ProblemCheckCompleteBottomSheetFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-214] 총 운동 시간이 표시 되지 않는 버그 수정

---

Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-221] 기록 저장 취소 버튼 위치 변경

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift
Cllog/Projects/CllogService/Features/ReportFeature/Sources/Presentation/ReportView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-223] 리포트 뿌듯했던 도전 성공, 실패 Chip 제거

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ReportVideoImageView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-231] 바텀시트 썸네일 출력되지 않는 현상 수정

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarDayResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Calendar/CalendarStoryResponseDTO.swift
Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarDay.swift
Cllog/Projects/CllogService/Domains/CalendarDomain/Sources/Entity/CalendarStory.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarFeature.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Calendar/CalendarView.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/ClimbingCard.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/Component/DayView.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/DayBottomSheet/DayBottomSheet.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoFeature.swift
Cllog/Projects/CllogService/Features/CalendarFeature/Sources/Presentation/UserInfo/UserInfoView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-208] 캘린더 관련 버그 수정

---

Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-218] 이용약관, 개인정보 웹 URL 변경

---

Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-243] 저장 연속 클릭되는 현상 수정

---

Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Folder/FolderFeature.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Folder/FolderView.swift

-
- https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1/backlog?selectedIssue=SPS-213
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-213] 검색 필터링 선택 상황에서 재진입 시 발생하는 문제 해결

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Request/Story/ProblemRequestDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Problem/RegisterProblemResponseDTO.swift
Cllog/Projects/CllogService/Data/Data/Sources/DataSource/Remote/StoriesDataSource.swift
Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultProblemRepository.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Repository/ProblemRepository.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/RegisterProblemUseCase.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/RecordHomeFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/UserDefault/VideoDataManager.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-244] 난이도 변경 이슈 해결

---

Cllog/Projects/CllogService/Data/Starlink/Sources/Request/Request.Response.swift

- retry 후 실패시 errorhandler를 타지 않는 로직 수정

[kickout] upload api 호출시 킥아웃 로직 추가

---

Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

api 파라미터 타임스탬프 추가

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/AVPlayerClient.swift
Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift

-
- https://depromeet-16-5.atlassian.net/browse/SPS-234
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-234][영상 편집] 두번째 편집 시도시 영상 재생만 가능한 이슈

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/SharedView/InstagramSharerView.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptView.swift

[shared] 인스타그램 공유하기 기능 추가

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditView.swift

- 툴팁 외 화면 선택 시 안넘어감 수정
- https://depromeet-16-5.atlassian.net/browse/SPS-254
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-254][영상 편집] 툴팁 외 화면 선택 시 안넘어감 수정

---

Cllog/Projects/CllogService/Data/Data/Sources/DataMapping/Response/Stories/Summary/StorySummaryResponseDTO.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/Entity/Summary/StorySummary.swift
Cllog/Projects/CllogService/Domains/StoryDomain/Sources/UseCase/FetchStoryUseCase.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Demo/Resources/Sample.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Demo/Sources/App.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Interface/Sources/Sample.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Project.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Sources/Presentation/CompletionReportFeature.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Sources/Presentation/CompletionReportView.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Test/Sources/Sample.swift
Cllog/Projects/CllogService/Features/CompletionReportFeature/Tests/Sources/Sample.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoFeature.swift
Cllog/Projects/CllogService/Service/Project.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Main/MainFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/Path.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterFeature.swift
Cllog/Projects/CllogService/Service/Sources/Presentation/Router/RouterView.swift
Cllog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-230] 영상 촬영 최종 결과, 공유 기능 추가

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift

-
- https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-246
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-246] 이미지 비율 수정

---

Cllog/Projects/CllogService/CoreKit/Core/Sources/View/VideoPlayerView/VideoPlayerView.swift

-
- https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-248] 영상 로드 후 자동 재생

---

Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift

[window] portrait

---

Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/NearByCragUseCase.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

hotfix: 근처 암장 다음 페이지 위치 nil 처리

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift

-
-  https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-246
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-246] 썸네일 없는 경우 이미지 이상하게  뜨는 이슈 해결

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Button/RecodingButton.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recording/RecordingView.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/UserDefault/VideoDataManager.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Video/VideoView.swift

- 영상 편집 가이드 툴팁 없음 수정
- https://depromeet-16-5.atlassian.net/browse/SPS-255
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-255][영상 촬영] 영상 편집 가이드 툴팁 없음 수정

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift

- 편집 취소 -> 저장안함시 영상 자동재생 안됨 이슈 수정
- https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1/backlog?selectedIssue=SPS-266
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-266] [영상 편집] 편집 취소 -> 저장안함시 영상 자동재생 안됨 이슈 수정

---

Cllog/Projects/CllogService/CoreKit/Core/Sources/Helper/MediaHelper.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-257] 영상 삭제 안내

---

Cllog/Projects/CllogService/Features/CompletionReportFeature/Sources/Presentation/CompletionReportView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-271] 이미지 최대 크기 늘어나서 뷰 밖으로 벗어나는 현상 수정

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

Fix: 영상 회전 이슈 해결

---

Cllog/Projects/CllogService/Features/LoginFeature/Sources/LoginFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-272] 카카오 로그인중 취소시 앱이 죽는 현상

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/Thumnail/Thumbnail.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-274] 썸네일 공통 컴포넌트 작업

---

Cllog/Projects/CllogService/Features/EditFeature/Sources/Presentation/VideoEditFeature.swift

- 실행 취소 후 다시실행 시, 스탬프 찍힘 이슈 수정
- https://depromeet-16-5.atlassian.net/browse/SPS-240
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-240][영상 편집] 실행 취소 후 다시실행 시, 스탬프 찍힘 이슈 수정

---

Cllog/Projects/AppModule/Sample/Sources/Core/AppDelegate.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/Services/Location.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/Services/LocationFetcher.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/NearByCragUseCase.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Modules/Shared/Sources/Extension/Resolver+.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift
Cllog/Projects/CllogService/Service/Sources/Services/Location/DefaultLocationFetcher.swift
Cllog/Projects/CllogService/Service/Sources/Services/Location/LocationError.swift
Cllog/Tuist/ProjectDescriptionHelpers/Configuration/InfoPlist.swift

- 암장 위치 기반 검색
- 위치 없을 때 설정 이동 / 위치 검색 실패 시 처리 따로 없슴다
- https://depromeet-16-5.atlassian.net/jira/software/projects/SPS/boards/1?selectedIssue=SPS-224
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-224] 위치 기반 암장 검색

---

Cllog/Projects/CllogService/Domains/Domain/Sources/Services/LocationFetcher.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/NearByCragUseCase.swift
Cllog/Projects/CllogService/Features/FolderFeature/Sources/Presentaition/Attempt/AttemptFeature.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift
Cllog/Projects/CllogService/Service/Sources/DI/ClLogServiceAssembly.swift

- 
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

[SPS-224] 위도 경도 버그 수정

---

Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/Main/SettingFeature.swift
Cllog/Projects/CllogService/Features/SettingFeature/Sources/Presentation/UIModel/SettingItemType.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

Feat: 의견 보내기 페이지 연결

---

Cllog/Projects/CllogService/CoreKit/DesignKit/Sources/Component/View/ThumbnailView.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

Fix: 탭 영역 수정

---

Cllog/Projects/CllogService/Data/Data/Sources/Repository/DefaultNearByCragRepository.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/Repository/NearByCragRepository.swift
Cllog/Projects/CllogService/Domains/Domain/Sources/UseCase/NearByCragUseCase.swift
Cllog/Projects/CllogService/Features/VideoFeature/Sources/Record/Recorded/RecordedFeature.swift

-
-
관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |

wip: 암장 커서 초기화되는 문제 임시 해결

---

Clog/Projects/ClogService/CoreKit/Core/Sources/FeatureAction.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Demo/Resources/Sample.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Demo/Sources/App.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Demo/Sources/AppDelegate.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Interface/Sources/Sample.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Project.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Sources/Sample.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Test/Sources/Sample.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Tests/Sources/Sample.swift
Clog/Projects/ClogService/Service/Project.swift
Clog/Tuist/ProjectDescriptionHelpers/Extension/Dependency+Feature.swift

- [이슈 링크](https://depromeet-16-5.atlassian.net/jira/software/projects/PLT/boards/3?selectedIssue=PLT-5)
<br>
- 프로필 편집 모듈 생성
- FeatureAction Protocol 작업
<br>
📸 관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |
<br>
-

[PLT-5] 프로필 편집 모듈 생성 및 FeatureAction 작업

---

Clog/Projects/ClogService/CoreKit/DesignKit/Sources/Component/View/SocialProfileImageView.swift
Clog/Projects/ClogService/Domains/SocialDomain/Sources/Entity/SocialFriend.swift
Clog/Projects/ClogService/Features/SocialFeature/Interface/Sources/SocialTabFeature.swift
Clog/Projects/ClogService/Features/SocialFeature/Sources/Social/Components/SocialFriendListCell.swift
Clog/Projects/ClogService/Features/SocialFeature/Sources/Social/Components/SocialTabView.swift
Clog/Projects/ClogService/Features/SocialFeature/Sources/Social/SocialView.swift

- [이슈 링크]()
<br>
- 소셜 메인 UI작업을 마쳤습니다
<br>
📸 관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |
<br>
-

[PLT-8] ProfileUI작업

---

Clog/Projects/ClogService/Data/Data/Sources/DataMapping/Request/Account/EditUserRequestDTO.swift
Clog/Projects/ClogService/Data/Data/Sources/DataMapping/Response/Account/UserResponseDTO.swift
Clog/Projects/ClogService/Data/Data/Sources/DataSource/Remote/UserDataSource.swift
Clog/Projects/ClogService/Data/Data/Sources/Repository/DefaultAccountRepository.swift
Clog/Projects/ClogService/Domains/AccountDomain/Sources/Entity/EditUserRequest.swift
Clog/Projects/ClogService/Domains/AccountDomain/Sources/Entity/User.swift
Clog/Projects/ClogService/Domains/AccountDomain/Sources/Repository/AccountRepository.swift
Clog/Projects/ClogService/Domains/AccountDomain/Sources/UseCase/Account/AccountUseCase.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Interface/Sources/ProfileEditorFeature.swift
Clog/Projects/ClogService/Features/ProfileEditorFeature/Sources/ProfileEditorView.swift

- [이슈 링크]()
<br>
-
<br>
📸 관련 로그, 스크린샷
---
| 작업전 | 작업후 |
| --- | --- |
<br>
-

[PLT-9] 프로필 수정 API 작업

---

Clog/Projects/ClogService/Data/Data/Sources/DataMapping/Response/Social/SocialFriendResponseDTO.swift
Clog/Projects/ClogService/Data/Data/Sources/DataSource/Remote/SocialFriendDataSource.swift
Clog/Projects/ClogService/Data/Data/Sources/Repository/DefaultSocialFriendRepository.swift
Clog/Projects/ClogService/Domains/SocialDomain/Sources/Entity/SocialFriend.swift
Clog/Projects/ClogService/Domains/SocialDomain/Sources/Repository/SocialFriendRepository.swift
Clog/Projects/ClogService/Features/SocialFeature/Interface/Sources/SocialFeature.swift
Clog/Projects/ClogService/Features/SocialFeature/Interface/Sources/SocialTabFeature.swift
Clog/Projects/ClogService/Features/SocialFeature/Sources/Social/Components/SocialTabView.swift
Clog/Projects/ClogService/Features/SocialFeature/Sources/Social/SocialView.swift

- [jira](https://depromeet-16-5.atlassian.net/jira/software/projects/PT/boards/2?selectedIssue=PT-11)
<br>
- 팔로우 목록 조회
- 팔로잉 / 언팔로잉
- UI업데이트 완료
<br>
📸 관련 로그, 스크린샷
---
https://github.com/user-attachments/assets/52e7ef21-fd5b-4828-b842-c370a7e4722f
<br>

[Feat] 팔로잉 기능 연결
